// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvIMQLOcJB1Qu7dGn190e5xQMxmLuoi8s',
    appId: '1:476812542881:web:8ae27388f467be8267c1e0',
    messagingSenderId: '476812542881',
    projectId: 'helloo-myyy',
    authDomain: 'helloo-myyy.firebaseapp.com',
    storageBucket: 'helloo-myyy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3WHmF6MhEqw8cS7VZwhJ2QY-swcsUxg',
    appId: '1:476812542881:android:a473abedaab37d6a67c1e0',
    messagingSenderId: '476812542881',
    projectId: 'helloo-myyy',
    storageBucket: 'helloo-myyy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3IzUWEUJlr-cigWD0bpYtDEUP8NopASg',
    appId: '1:476812542881:ios:383deff05b1e726367c1e0',
    messagingSenderId: '476812542881',
    projectId: 'helloo-myyy',
    storageBucket: 'helloo-myyy.firebasestorage.app',
    iosBundleId: 'com.example.myTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3IzUWEUJlr-cigWD0bpYtDEUP8NopASg',
    appId: '1:476812542881:ios:383deff05b1e726367c1e0',
    messagingSenderId: '476812542881',
    projectId: 'helloo-myyy',
    storageBucket: 'helloo-myyy.firebasestorage.app',
    iosBundleId: 'com.example.myTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvIMQLOcJB1Qu7dGn190e5xQMxmLuoi8s',
    appId: '1:476812542881:web:a54c9d8f8d9cce2767c1e0',
    messagingSenderId: '476812542881',
    projectId: 'helloo-myyy',
    authDomain: 'helloo-myyy.firebaseapp.com',
    storageBucket: 'helloo-myyy.firebasestorage.app',
  );
}
